from app.schemas.common import APIResponse, PaginatedResponse, HealthResponse
from app.schemas.user import UserBase, UserRegister, UserLogin, UserResponse, Token, TokenPayload
from app.schemas.job import (
    JobSkillBase,
    JobSkillCreate,
    JobSkillResponse,
    JobBase,
    JobCreate,
    JobUpdate,
    JobResponse,
    JobListResponse,
)
from app.schemas.candidate import (
    CandidateSkillBase,
    CandidateSkillCreate,
    CandidateSkillResponse,
    CandidateBase,
    CandidateCreate,
    CandidateUpdate,
    CandidateResponse,
    CandidateUploadResponse,
)

__all__ = [
    "APIResponse",
    "PaginatedResponse",
    "HealthResponse",
    "UserBase",
    "UserRegister",
    "UserLogin",
    "UserResponse",
    "Token",
    "TokenPayload",
    "JobSkillBase",
    "JobSkillCreate",
    "JobSkillResponse",
    "JobBase",
    "JobCreate",
    "JobUpdate",
    "JobResponse",
    "JobListResponse",
    "CandidateSkillBase",
    "CandidateSkillCreate",
    "CandidateSkillResponse",
    "CandidateBase",
    "CandidateCreate",
    "CandidateUpdate",
    "CandidateResponse",
    "CandidateUploadResponse",
]
